### ISSUE TITLE
Error message in GK4 Weather

### ISSUE THREAD

**Issue by kaiserf** [GavickPro/Weather#21]
Dear Sir or Madam,

I have carried out an update in Joomla 3.x and another update in JSN Editor. After the update the following error message in GK4 Weather has been displayed.

![error](https://cloud.githubusercontent.com/assets/12393177/7563216/33d1807a-f7db-11e4-9f48-094e9ae6aa60.JPG)

I hope you can help me with my problem.

Sincerely yours
Franz Kaiser

**Comment by dziudek** [comment]
Hello,

Please read: https://www.gavick.com/documentation/uncategorized/how-to-fix-strict-standards-non-static-method
