### ISSUE TITLE
weather module only showing Question Marks

### ISSUE THREAD

**Issue by Cpointcc** [GavickPro/Weather#26]
My module was working fine last week and now this week before and after any updates it is only displaying question marks.  Please advise.
![gk4-weather-module-displays-question-marks](https://cloud.githubusercontent.com/assets/18144058/14109609/6e1139b4-f588-11e5-8ea0-e4597d7869c8.jpg)

This is happening on every website I have it on.

**Comment by dziudek** [comment]
Hello,

The update will be ready in today's evening

**Comment by dziudek** [comment]
Please try to install this version: https://github.com/GavickPro/Weather/releases/tag/v.1.7.2

**Comment by Cpointcc** [comment]
I have installed this version and it hasn’t changed.  Still showing question marks.

[cid:image001.jpg@01D189BC.D62C4EE0]

Sue Grady
IT Specialist/Web Developer
815-223-1052
815-223-0791 Fax
sgrady@cpointcc.com

**Comment by Cpointcc** [comment]
Notice: Undefined index: current_temp in /home/ivnetcom/public_html/modules/mod_weather_gk4/tmpl/yahooView.php on line 26
Peru

 *
Notice: Undefined offset: 0 in /home/ivnetcom/public_html/modules/mod_weather_gk4/tmpl/yahooView.php on line 42

Notice: Undefined offset: 0 in /home/ivnetcom/public_html/modules/mod_weather_gk4/tmpl/yahooView.php on line 52

Notice: Undefined offset: 0 in /home/ivnetcom/public_html/modules/mod_weather_gk4/tmpl/yahooView.php on line 53

 *
Notice: Undefined offset: 1 in /home/ivnetcom/public_html/modules/mod_weather_gk4/tmpl/yahooView.php on line 42

Notice: Undefined offset: 1 in /home/ivnetcom/public_html/modules/mod_weather_gk4/tmpl/yahooView.php on line 52

Notice: Undefined offset: 1 in

[cid:image001.jpg@01D189BD.242E8DB0]

Sue Grady
IT Specialist/Web Developer
815-223-1052
815-223-0791 Fax
sgrady@cpointcc.com

**Comment by Cpointcc** [comment]
OK – sorry – it appears to be working now.

Thank you!
[cid:image001.jpg@01D189BD.CAB0E570]

Sue Grady
IT Specialist/Web Developer
815-223-1052
815-223-0791 Fax
sgrady@cpointcc.com
