### ISSUE TITLE
Weather Module for Joomla not working

### ISSUE THREAD

**Issue by ismaelhaider** [GavickPro/Weather#31]
Hi folks, I installed today weather module which I downloaded from github today, now my site is showing white blank page. nothing works. Can you check what is the issues?

Thanks

**Comment by dziudek** [comment]
Hello, please enable displaying PHP errors - you can do it under global configuration in the server tab - without it we are unable to find reason of your problems.

**Comment by ismaelhaider** [comment]
Hi ,

I enabled PHP errors, Now its showing xmp parser error, Here is the link and screenshot

http://imgur.com/3LxxBkg

http://ihlabspro.com/demos/index.php?lang=en

**Comment by dziudek** [comment]
It seems that you have downloaded module for Joomla! 2.5. Please always install packages from the release pages: https://github.com/GavickPro/Weather/releases/tag/v.1.7.3
