### ISSUE TITLE
Weather Module for STOP SHOWING Temperature

### ISSUE THREAD

**Issue by ismaelhaider** [GavickPro/Weather#32]
Hi, for Weather, I notice 1 things, Temperature in weather is disappear when i refresh page, maybe there is change in yahoo API, can you please check and update.

Thanls

**Comment by dziudek** [comment]
Sorry but I cannot reproduce your issue - please try to set cache time in the module.

**Comment by ismaelhaider** [comment]
Hi folks,

Its working now.i dont know the issue but its working .thanks for great extention.
